#!/bin/sh
set -eu

device_path=${1:-}
telemetry_user=${2:-leo}
sysfs_root=${POWER_CAP_SYSFS_ROOT:-/sys}
setfacl_bin=${POWER_CAP_SETFACL:-/usr/bin/setfacl}

case "${device_path}" in
  /devices/virtual/powercap/*) ;;
  *) exit 0 ;;
esac

domain_root="${sysfs_root}${device_path}"
[ -r "${domain_root}/name" ] || exit 0
[ -e "${domain_root}/energy_uj" ] || exit 0

domain_name=$(sed -n '1p' "${domain_root}/name")
case "${domain_name}" in
  psys|package-0)
    exec "${setfacl_bin}" -m "u:${telemetry_user}:r--" "${domain_root}/energy_uj"
    ;;
esac

exit 0
