#!/bin/sh
set -eu

script_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)

sudo install -o root -g root -m 0755 "${script_dir}/big-red-powercap-read" /usr/local/sbin/big-red-powercap-read
sudo install -o root -g root -m 0440 "${script_dir}/../sudoers.d/big-red-powercap-telemetry" /etc/sudoers.d/big-red-powercap-telemetry
sudo visudo -cf /etc/sudoers.d/big-red-powercap-telemetry >/dev/null

# Remove the superseded ACL approach, which sysfs rejects on Big Red's kernel.
sudo rm -f /etc/udev/rules.d/90-big-red-powercap-telemetry.rules /usr/local/sbin/big-red-powercap-access
sudo udevadm control --reload-rules
sudo -n /usr/local/sbin/big-red-powercap-read >/dev/null
